### ISSUE TITLE
Add Wrap up session page with questionnaire before final page

### ISSUE THREAD

**Issue by zwang39-1936420** [CoExLab/pinmi#88]
![image](https://github.com/CoExLab/pinmi/assets/75330989/20bc883c-c5c5-43a8-bd75-70027631df0f)

**Comment by dabbish** [comment]
@dabbish will look into script for downloading results from session

**Comment by eddie-tui-wang** [comment]
Current solution: Add a button that navigate users to the Qualtrics questionnaire. 
 

![Image](https://github.com/CoExLab/pinmi/assets/75330989/8cbef289-9e55-4826-b762-0f1e3fedc460)

**Comment by eddie-tui-wang** [comment]
[ucre-control] fixed completion page, deleted Pin-mi 


![Image](https://github.com/CoExLab/pinmi/assets/75330989/d552f6ea-3101-4146-920f-aa52f62b82b0)

changed to this


![Image](https://github.com/CoExLab/pinmi/assets/75330989/bcb0f24e-d856-4a8f-852e-b9a6a4ce5300)
